apiVersion: apps/v1

kind: Deployment

metadata:

  name: calc-app

  labels:

    app.kubernetes.io/name: calc-app
    app: calc-app

spec:

  replicas: 1

  selector:

    matchLabels:

      app.kubernetes.io/name: calc-app
      app: calc-app

  template:

    metadata:

      labels:

        app.kubernetes.io/name: calc-app
        app: calc-app

    spec:

      containers:

        - name: calc-app

          image: shlomokallner613/bank-leumi-entrance-exam-calc:latest

          ports:

            - containerPort: 80
          
          limits:
            
